name: kataho_code
description: Convert Nepal Plus Codes into human-readable Kataho Codes.
version: 0.1.1
repository: https://github.com/addressgraph-nepal/kataho_codes
homepage: https://github.com/addressgraph-nepal/kataho_codes
issue_tracker: https://github.com/addressgraph-nepal/kataho_codes/issues

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.1.0
  encrypt: ^5.0.3
  flutter_bloc: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/data/nepal_geocode.json.enc
    - assets/data/geocode_words.json.enc
    - assets/data/geocode_number_suffixes.json.enc
